---
title: "PROBABILITY DENSITY ESTIMATION"
subtitle: "Chapter 12 SCR2e, Part 1"
author: "AG Schissler"
date: "13 Apr 2021 (*updated: `r Sys.Date()`)*"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r LoadLib, echo = FALSE, eval = TRUE, message=FALSE, warning=FALSE, results = "hide"}
set.seed( 04132021 )
library(tidyverse)
library(printr)
## xaringan::inf_mr('21_ch12_DensityEst1.Rmd')
## str(knitr::opts_chunk$get())
```

<!-- open up etext as you go. don't typeset the chapter -->

# i. Week 12 Focus

- Students Practice on Ch. 11 content.
- Students receive and act on Ch. 10 feedback.
- Read Prob Den. Est. Ch. 12.
- Discuss Prob Den. Est.  Ch. 12.

## Any questions on Ch.11 HW?

- 11.1, 11.2 M-H practice and understanding.
- 11.5 MCMC in Bayesian inference.
- 11.10 Gibbs with full conditionals available.
- 11.12 Convergence diagnostics
- ~~11.15 Change Point and HPDI.~~

## Today's plan

1. Finish Ch.11 MCMC discussion
   * Bayesian posterior M-H derivation
   * Gibbs sampler explained
   * Gibbs sampler acceptance rate = 1.
   * `coda`
   * Modern MCMC / 
2. Discuss on Ch. 12 Problem Set to prime learning.
3. Discuss Ch. 12 Prob Den. Est. part 1
4. Summarize, conclude, revisit Ch. 12 Problem prompt discussion / hints time remaining

*Please contribute questions and comments*

# I. Ch.12 HW

- 12.1 Histogram estimation
- 12.4 Frequency polygon density
- 12.6 ASH density for old faithful
- 12.8 Kernel density for `buffalo` snowfall data.
- 12.13 Generalize 2D ASH.

# Ch. 12 Probability Density Estimation

## Probability Density Estimation, Part 1

* Overview
* 12.1 Univariate Density Estimation
  * 12.1.1 Histograms
	* Sturge's Rule
	* Example 12.1
	* Example 12.2
	* Scott's Normal Reference Rule 
	* Example 12.3
	* Freedman-Diaconis Rule
  * 12.1.2 Frequency Polygon Density Estimate
	* Example 12.4
  * 12.1.3 The Averaged Shifted Histogram
    * Example 12.5
	* Example 12.6

# Overview

- Motivation
- Big ideas

# 12.1 Univariate Density Estimation

## 12.1.1 Histograms
	
## Sturge's Rule
	
## Example 12.1
	
## Example 12.2

## Scott's Normal Reference Rule 

## Example 12.3
	
## Freedman-Diaconis Rule
 
## 12.1.2 Frequency Polygon Density Estimate

## Example 12.4

## 12.1.3 The Averaged Shifted Histogram

## Example 12.5

## Example 12.6

# Closing / Ch. 12 Problem set

- Revisit HW.
- Questions?
- Students please summarize/ask questions about what we discussed today.
