---
title: "PROGRAMMING TOPICS"
subtitle: "Chapter 15 SCR2e"
author: "AG Schissler"
date: "27 Apr 2021 (*updated: `r Sys.Date()`)*"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r LoadLib, echo = FALSE, eval = TRUE, message=FALSE, warning=FALSE, results = "hide"}
set.seed( 04272021 )
library(tidyverse)
library(printr)
## xaringan::inf_mr('25_ch15_ProgrammingTopics.Rmd')
## str(knitr::opts_chunk$get())
```

<!-- open up etext as you go. don't typeset the chapter -->

# i. Week 14 Focus

- Students draft/edit Final Exam poster; topic should clearly defined and approved.
- Students Practice on Ch.13,14 content.
- Students receive and act on Ch.12 feedback.
- Read Programming Topics Ch.15.
- Discuss Ch.15.

## Today's plan

i. Feedback from HW Ch.12
ii. Ch.13,14 HW discussion
iii. Discuss Ch.15 Programming Topics
iii. Summarize Ch.15

*Please contribute questions and comments*

## i. Projects

- How are things coming along?
- Still looking for a project? Interesting paper just came out:
*Iterative Likelihood: A Unified Inference Tool* Haiying Wang,Dixin Zhang,Hua Liang &David Ruppert
- Brainstorm with anyone right now?
- Discussion over email correspondence?

## ii. Feedback from HW Ch.12

- 12.1 Binwidths
- 

# iii. Ch.13,14 HW discussion

## Any questions on Ch.13,14 HW?

- 13.3 Efficient implementation a high dimension, computationally intense procedure.
- 13.4 Computing critical values for a nonstandard statistical procedure. Hint: work with the difference and find 1D root. Note the function is well defined for $|a| \leq k$.
- 13.5 Computing critical values for a nonstandard statistical procedure II. Hint: connect to your answer from 13.4 by noticing the distribution functions appearing in the equation. How can you represent this in terms of CDFs? Then the calculation will be trivial.
- 14.1 Use the *simplex* algorithm to solve a small system of equations. Use `boot::simplex()`.

# iv. Ch.15 Programming Topics

- 15.1 Introduction
- 15.2 Benchmarking: Comparing execution time of code, `microbenchmark` package.
- 15.3 Profiling
- 15.4 Object size, Attributies, and Equality
- 15.5 Finding source code
- 15.6 Linking to C/C++ Code using `Rcpp`
- 15.7 Application: Baseball data

## 15.1 Introduction

- *Advanced R* is a practical guide by Wickham, available free online
- Also see *R packages* for creating R packages easily

## 15.2 Benchmarking: Comparing execution time of code

- `system.time()`
- `proc.time()`
- Ex 15.1 `microbenchmark` package.
- Ex 15.3 `rbenchmark` package.

## 15.3 Profiling

- Finding bottlenecks `Rprof`

## 15.4 Object size, Attributies, and Equality

- Memory management

## 15.5 Finding source code

- Easy when all in R
- Use methods for compiled code.

## 15.6 Linking to C/C++ Code using `Rcpp`

- Fast R by not using R.


## 15.7 Application: Baseball data

- `tidyverse`
- See *R for Data Science* another excellent online book by Wickham.

# Closing

- Revisit HW.
- Questions?
- Students please summarize/ask questions about what we discussed today.
- `Python` is a popular and capable language for stats `numpy`, `pandas`, etc. Great tool and more features/general use than `R`.
- Try `Julia` for a high-performance, modern programming language with GPU acceleration, multi-core, JIT compiler, syntactic sugar, etc. 
