---
title: "STAT 745: Computational Methods in Statistics"
semester: "Spring 2021"
instructor: 'Alfred "Grant" Schissler, Ph.D.'
left_col:
  - field: "Email"
    value: "aschissler@unr.edu"
  - field: "Office Phone"
    value: "(775) 784-4661"
  - field: "Office Location"
    value: "DMS 224"
  - field: "Office Hours"
    value: "TBD"
  
right_col:
  - field: "Web"
    value: "<a href='https://www.grantschissler.com'>www.grantschissler.com</a>"
  - field: "Class Location"
    value: "Zoom / AB 110"
  - field: "Class Hours"
    value: "TuTh 4:30pm to 5:45pm"
output: 
  html_document:
    css: style.css
    template: template.html
    self_contained: true
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
library(tidyverse)
mon <- as.Date("2021-01-25")
# fri <- as.Date("2016-01-08")
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}
```

# Course Description

Techniques of advanced computational statistics. 
Numerical optimization and integration pertinent for statistical calculations; simulation and Monte Carlo methods including Markov chain Monte Carlo (MCMC); bootstrapping; smoothing/density estimation; and other modern topics.
Computing using statistical software. Resampling and simulation: bootstrap, Monte Carlo, and Markov chain methods. Numerical inference for non-standard models. Bayesian inference. Advanced graphics.

*Instructor's role*

- Help explain and guide student understanding and skill development.
- Organize the course structure and assignments.
- Lead weekly class discussions.
- Evaluate student work and provide feedback.

*Student's role*

- Complete the readings before the week's discussion meeting.
- Submit completed assignments on time.
- Participate in discussions. 
- Prepare for and complete course exams.

# Course Prerequisites

STAT 667 or STAT 754 or STAT 726; Recommended Preparation: STAT 645; MATH 330.

# Student Learning Outcomes

Upon completion of this course, students will be able to:  

1. organize and present information in graphical and numerical forms to support concise, comprehensible, and scientifically defensible written conclusions/knowledge to research problems.  
2. create computational solutions to answer statistical questions for traditional and non-standard models using a high-level programming language.  
3. organize computational research findings in a professional report suitable for presentation to a variety of audiences.  

# Textbooks

*Required text*

*Statistical Computing with R*, Second Edition, by Maria L. RIZZO.
[Textbook website](https://www.routledge.com/Statistical-Computing-with-R-Second-Edition/Rizzo/p/book/9781466553323)

**MAKE SURE TO GET THE 2nd EDITION**

Github with resources

```{bash cloneGit, eval=F, include=T}
git clone https://github.com/mariarizzo/SCR.git
```

Errata
SCR/SCR-2e/SCR2e-errata.pdf

*Supplemental texts*.

Classical Introduction to `R` programming:  
https://cran.r-project.org/doc/contrib/Owen-TheRGuide.pdf

Modern best practices for coding and reporting `R` analyses:  
*R for data science: import, tidy, transform, visualize, and model data*, Hadley WICKHAM and Garrett GROLEMUND.
[Online textbook](https://r4ds.had.co.nz/)

*Mastering `R` and `RStudio`*

https://education.rstudio.com/learn/beginner/

https://education.rstudio.com/learn/intermediate/

https://education.rstudio.com/learn/expert/

# Attendance

Students are expected to attend class.
If important circumstances prevent this, it is the student's responsibility to find out what was covered in class, what was assigned for reading or homework, and what special announcements (if any) were made.
"Excessive absence" in this class will be construed to be absence from more than 10 percent of the scheduled class sessions, whether excused or unexcused.

# Assignments

## Problem sets

Problem sets will be assigned approximately weekly due on Fridays. You are encouraged to discuss assignments between each other and with instructor. However, the assignment must be completed and submitted individually. 

## Midterms
There will be one take-home midterm, due Friday, 26 Feb 2021. 

## Final exam
There will be a take-home final exam, due Friday, 7 May 2021. 

## Exam policy

Exams will be released roughly a week to before the due date. You must complete the exams without help. See Canvas for more details on take-home examination procedures.

## Makeup, Late Policy

* Problem sets solutions and completed exams are due on Fridays.
* Late assignments/exams will be given a 20% penalty per business day received late. (i.e., Saturday -0%, Sunday -0%, Monday -20% , Tuesday -40%, ..., Friday -100%).
* Exceptions will be made when a student misses work due to a documented (doctor's note) illness or an extraordinary situation (up to the discretion of the instructor). 
* There will be no early or make-up exams. 
* If you need to miss an exam due to participation in a religious holiday or an official university activities (including athletics and other sanctioned activities), you must make arrangements with the instructor at least two weeks prior to the exam in question. 

**I'll drop (trim) your 2 lowest grades in the "Problem Set" category to protect against 1-2 outlying points having too much weight (e.g., a 0).**

# Grading

We'll use a weighted categorical system to evaluate student learning. There are three categories of assignments. Table 1 shows the percentages for each category and the number of assignments (n).

| Assignment | n  | %  |
|------------|----|----|
| Problem set  | 13 | 60 |
| Midterm    | 1  | 15 |
| Final Exam | 1  | 25 |

Table 2 displays the letter grade conversion for the total score from Table 1.

| Letter grade | % Range      |
|--------------|--------------|
| A            | 89.9 - up    |
| B            | 79.9 - 89.8  |
| C            | 69.9 - 79.8  |
| D            | 59.9 - 69.8  |
| F            | below - 59.8 |

The instructor reserves the right to deviate from the above thresholds, including assigning $+$ or $-$.

# Diversity Statement

The University of Nevada, Reno is committed to providing a safe learning and work environment for all. If you believe you have experienced discrimination, sexual harassment, sexual assault, domestic/dating violence, or stalking, whether on or off campus, or need information related to immigration concerns, please contact the University’s Equal Opportunity & Title IX Office at (775) 784-1547. Resources and interim measures are available to assist you. For more information, please visit [http:www.unr.edu/equal-opportunity-title-ix](http:www.unr.edu/equal-opportunity-title-ix).

# Disability Statement
Any student with a disability needing academic adjustments or accommodations is requested to speak with the [http:www.unr.edu/drc](Disability Resource Center) as soon as possible to arrange for appropriate accommodations.

# Academic Conduct
No laptops, cell phones, mp3 players, or other electronics are to be used for personal reasons in class. If you are being disruptive during class you will be asked to leave. Disruptions in this context include inadequate participation. You must come to class on time and stay until the end of lecture. Tardy students will not be admitted to class. Please visit [http:www.unr.edu/student-conduct](http:www.unr.edu/student-conduct) for our official student code of conduct.

# Academic Success Services
Your student fees cover usage of the University Math Center, University Tutoring Center, and University Writing Center. These centers support your classroom learning; it is your responsibility to take advantage of their services. Keep in mind that seeking help outside of class is the sign of a responsible and successful student.

# University Recording Policy
Surreptitious or covert videotaping of class or unauthorized audio recording of class is prohibited by law and by Board of Regents policy. This class may be videotaped or audio recorded only with the written permission of the instructor. In order to accommodate students with disabilities, some students may have been given permission to record class lectures and discussions. Therefore, students should understand that their comments during class may be recorded.

# Academic Dishonesty
Cheating, plagiarism, or otherwise obtaining grades under false pretenses constitutes academic dishonesty according to the code of this university. Academic dishonesty will not be tolerated and penalties can include canceling a student’s enrollment without a grade or giving an F for the assignment or for the entire course. See the University Academic Standards policy: [UAM 6,502](https://www.unr.edu/administrative-manual/6000-6999-curricula-teaching-research/instruction-research-procedures/6502-academic-standards).

# Tentative course schedule

Students please study the materials before the assigned class session.
Class readings and assignments are subject to change, contingent on mitigating circumstances and the progress we make as a class.

<div class="week">`r advdate(mon, 1)`: Introduction to STAT 745, Ch. 1 </div>

- Readings: Read Rizzo Ch. 1.
- Practice: Work on Ch. 1 Problem Set and compiling `rmarkdown` documents.
- Exams: None.
- Notes: None.

*Tuesday topic*: Welcome to 745! We'll discuss the structure of the course and expectations for students/instructor.   
*Thursday topic*: Ch. 1 Introduction and computing tools / workflows

<div class="week">`r advdate(mon, 2)`: Probability and Statistics Review, Ch. 2</div>

- Readings: Read Rizzo Ch. 2.
- Practice: Work on Ch. 1 Problem Set and compiling `rmarkdown` documents.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 2 Random variables, multivariate normal  
*Thursday topic*: Ch. 2 Limit theorems, statistics, Bayes' theorem, Markov chains  

<div class="week">`r advdate(mon, 3)`: Methods for generating random varibles, Ch. 3</div>

- Readings: Read Rizzo Ch. 3.
- Practice: Please complete Ch. 1 Problem Set and submit `rmd` and `html` files in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 3 Inverse transform, accept-reject, transformations  
*Thursday topic*: Ch. 3 Sums and mixtures, multivariate

<div class="week">`r advdate(mon, 4)`: Generating random processes, Ch. 4</div>

- Readings: Read Rizzo Ch. 4.
- Practice: Please complete Ch. 3 Problem Set and submit in Canvas by the end of the week.
- Exams: Midterm 1 released.
- Notes: None.

*Tuesday topic*: Ch. 4 Stochastic processes, Brownian motion  
*Thursday topic*: Ch. 4 Stochastic processes, Brownian motion

<div class="week">`r advdate(mon, 5)`: Multivariate Viz, Ch. 5 </div>

- Readings: Read Rizzo Ch. 5.
- Practice: Please complete Ch. 4 Problem Set and submit in Canvas by the end of the week.
- Exams: Midterm due Friday 26 2021
- Notes: None.

*Tuesday topic*: Ch. 5 Multivariate visualization  
*Thursday topic*: Reading Day. No class.

<div class="week">`r advdate(mon, 6)`: Monte Carlo integration and variance reduction, Ch. 6 </div>

- Readings: Read Rizzo Ch. 6.
- Practice: Please complete Ch. 5 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 6 MC Integration, variance reduction  
*Thursday topic*: Ch. 6 Antithetic variables, control variates, importance sampling, stratified sampling

<div class="week">`r advdate(mon, 7)`: Monte Carlo methods in inference, Ch. 7 </div>

- Readings: Read Rizzo Ch. 7.
- Practice: Please complete Ch. 6 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 7 MC estimation, testing, power  
*Thursday topic*: Ch. 7 MC estimation, testing, power

<div class="week">`r advdate(mon, 8)`: Bootstrap and jackknife, Ch. 8 </div>

- Readings: Read Rizzo Ch. 8.
- Practice: Please complete Ch. 7 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 8 Bootstrap and jackknife  
*Thursday topic*: Ch. 8 Bootstrap and jackknife

<div class="week">`r advdate(mon, 9)`: Resampling applications Ch. 9 </div>

- Readings: Read Rizzo Ch. 9.
- Practice: Please complete Ch. 8 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 9 jackknife-after-bootstrap, regression  
*Thursday topic*: Ch. 9 influence

<div class="week">`r advdate(mon, 10)`:  Permutation tests, Ch. 10 </div>

- Readings: Read Rizzo Ch. 10.
- Practice: Please complete Ch. 9 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 10 Tests of equal distribution, multivariate tests  
*Thursday topic*: Ch. 10 Applications

<div class="week">`r advdate(mon, 11)`:  Markov Chain Monte Carlo Methods, Ch. 11 </div>

- Readings: Read Rizzo Ch. 11.
- Practice: Please complete Ch. 10 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 11 Intro, Bayesian inference, MCMC integration  
*Thursday topic*: Ch. 11 Metropolis-Hastings, Gibbs, Convergence

<div class="week">`r advdate(mon, 12)`:  Probability Density Estimation, Ch. 12 </div>

- Readings: Read Rizzo Ch. 12.
- Practice: Please complete Ch. 11 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 12 Univariate density estimation, kernal density estimation  
*Thursday topic*: Ch. 12 Bi/multivariate estimation, other

<div class="week">`r advdate(mon, 13)`:  Numerical methods in R, Ch. 13 </div>

- Readings: Read Rizzo Ch. 13.
- Practice: Please complete Ch. 12 Problem Set and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Tuesday topic*: Ch. 13 root finding, integration  
*Thursday topic*: Ch. 13 maximum likelihood

<div class="week">`r advdate(mon, 14)`:  Optimization, Ch. 14 </div>

- Readings: Read Rizzo Ch. 14.
- Practice: Please complete Ch. 13 Problem Set and submit in Canvas by the end of the week.
- Exams: Final exam released.
- Notes: None.

*Tuesday topic*: Ch. 14 1D optimization, MLE  
*Thursday topic*: Ch. 14 2D, EM, simplex method

<div class="week">`r advdate(mon, 15)`:  Programming topics, Ch. 15 </div>

- Readings: Read Rizzo Ch. 15.
- Practice: Please complete Ch. 14 Problem Set and submit in Canvas by the end of the week.
- Exams: Final exam due 7 May 2021.
- Notes: None.

*Tuesday topic*: Ch. 15 benchmarking, profiling,   
*Thursday topic*: Ch. 15 `rcpp`, applications
