---
title: "Final Exam"
author: "STAT 745 Stats Comp (Spring 2021)"
date: "7 May 2021 (*updated: `r Sys.Date()`)*"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

## Poster competency matrix

```{r, echo = FALSE}
text_tbl <- data.frame(
  `Point Value Label` = c("Computation: Perform computations necessary for the data analysis", "Analysis: Choose and carry out analysis appropriate for data and context using the techniques you learned our textbook.", "Synthesis: Bring together the analysis and interpret results in context", "Visual: Communicate findings graphically clearly, precisely, and concisely", "Written: Communicate findings in writing clearly, precisely, and concisely"),
  `Needs Improvement` = c("Computations contain errors and extraneous code.", "Choice of analysis is overly simplistic, irrelevant, inappropriate for the data, or missing key component(s).", "Conclusions are missing, incorrect, or unsupported.", "Inappropriate choice of plots; poorly labeled plots; plots missing.", "Explanation is illogical, incorrect, or incoherent."),
  `Basic` = c("Computations correct but contain extraneous code/poorly organized/uncommented.","Analysis appropriate, but incomplete and important features and assumptions not made explicit","Conclusions are reasonable, but partially correct or partially complete.","Plots convey information correctly but lack context for interpretation.","Explanation is partially correct but incomplete or unconvincing."),
  `Exceeds standards` = c("Computations correct, clear, and properly labeled.","Analysis appropriate, complete, advanced, relevant, and informative.","Relevant conclusions explicitly connected to analysis and context.","Plots convey information correctly with adequate and appropriate connections.","Explanation is correct, complete, and convincing."),
  x = as.numeric(c( "10", "10", "5", "5", "5")),
  score = c("", "", "", "", "")
)
```
```{r, echo = FALSE}
library(kableExtra)

kable(text_tbl) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(6, bold = T, border_left = T, border_right = T) %>%
  add_header_above(c(" ", "1" , "2", "3", "",""), line_sep = 0, include_empty = T)


```
**Total Score (out of 100 points, 105 points possible):**
